=== KIZI/EasyMiner-XML/validation/ARBuilder0_1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://keg.vse.cz/ns/arbuilder0_1" xmlns:ar="http://keg.vse.cz/ns/arbuilder0_1"
    xmlns:arf="http://keg.vse.cz/ns/arfeatures_01" xmlns:guha="http://keg.vse.cz/ns/GUHA0.1rev1"
    xmlns:data="http://keg.vse.cz/ns/datadescription0_1" elementFormDefault="unqualified">
    <xs:import namespace="http://keg.vse.cz/ns/GUHA0.1rev1"
        schemaLocation="http://sewebar.vse.cz/schemas/GUHA0.1rev1.xsd"/>
    <xs:import namespace="http://keg.vse.cz/ns/datadescription0_1"
        schemaLocation="http://sewebar.vse.cz/schemas/DataDescription0_1.xsd"/>
    <xs:import namespace="http://keg.vse.cz/ns/arfeatures_01"
        schemaLocation="http://sewebar.vse.cz/schemas/GUHAARfeature.xsd"/>
    <xs:element name="ARBuilder">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="DataDescription" type="data:DataDescription"/>
                <xs:choice>
                    <xs:element name="ARQuery" type="ar:ARQuery"/>
                    <xs:element name="TaskSetting" type="guha:TaskSetting4ft"/>
                    <xs:element name="AssociationRules" type="guha:AssociationRules"/>
                    <xs:element name="QueryByAssociationRule" type="ar:QueryByAssociationRule"/>
                </xs:choice>
            </xs:sequence>
            <xs:attribute name="mode">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="TaskSetting"/>
                        <xs:enumeration value="ARQuery"/>
                        <xs:enumeration value="AssociationRules"/>
                        <xs:enumeration value="QueryByAssociationRule"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="procedure">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="4ft"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:annotation>
        <xs:documentation> Very similar to guha:TaskSetting, but some elements had to be redefined
            to make the schema more loose as what information is required </xs:documentation>
    </xs:annotation>
    <xs:complexType name="QueryByAssociationRule">
        <!-- it looks like guha AssociationRules element, but
             [1] DBA and BBA can be listed in mixed order
             [2] only one association rule allowed
        -->
        <xs:sequence>
            <xs:choice maxOccurs="unbounded">
                <xs:element type="ar:BBA" name="BBA"/>
                <xs:element type="guha:DBA" name="DBA"/>
            </xs:choice>
            <xs:element name="AssociationRule" type="ar:AssociationRule" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="AssociationRule">
        <!-- redefine  guha:AssociationRule  so that consequent is not mandatory-->
        <!-- redefine  guha:AssociationRule  so that IMValue is not mandatory-->
        <!-- redefine  guha:AssociationRule  so that FourFtTable is not present-->
        <xs:sequence>
            <xs:element name="Text" type="guha:Text" minOccurs="0"/>
            <xs:element name="IMValue" type="guha:IMValue" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="antecedent" type="guha:BARef"/>
        <xs:attribute name="consequent" type="guha:BARef"/>
        <xs:attribute name="condition" type="guha:BARef"/>
        <xs:attribute name="id" type="xs:NMTOKEN"/>
    </xs:complexType>
    <xs:complexType name="BBA">
        <xs:sequence>
            <xs:element name="Extension" type="guha:Extension" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="Text" type="guha:Text" minOccurs="0"/>
            <xs:element name="FieldRef" type="guha:FieldRef" minOccurs="1"/>
            <xs:element name="CatRef" type="guha:CatRef" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:NMTOKEN" use="required"/>
        <xs:attribute name="literal" type="xs:boolean" default="true"/>
        <xs:attribute name="weight" type="xs:double"/>
    </xs:complexType>

    <xs:complexType name="ARQuery">
        <xs:sequence>
            <xs:element name="BBASettings">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="BBASetting" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="Text" type="guha:Text" minOccurs="0"/>
                                    <xs:element name="Name" type="xs:string" minOccurs="0"/>
                                    <xs:element name="FieldRef" type="guha:FieldRef"/>
                                    <xs:element name="Coefficient" minOccurs="1" maxOccurs="1">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="Type" minOccurs="0"
                                                  type="arf:coefList"/>
                                                <xs:element name="Category" type="xs:string"
                                                  minOccurs="0" maxOccurs="unbounded"/>
                                            </xs:sequence>
                                            <xs:attribute name="match" type="ar:match">
                                                <!-- requireListed_exclusive, requireListed_notexclusive - complementWithUnlisted, traverseOnly (DBASetting only)- no match required but proceed to children, requirePresence (DBA Only)-->
                                            </xs:attribute>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                                <xs:attribute name="id" type="xs:NMTOKEN"/>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="DBASettings">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="DBASetting" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:complexContent>
                                    <xs:extension base="guha:DBASetting">
                                        <xs:attribute name="match" type="ar:match"/>
                                        <xs:attribute name="baRefsRecursive" default="false"
                                            type="xs:boolean"/>
                                    </xs:extension>
                                </xs:complexContent>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="AntecedentSetting" type="guha:BASettingRef" minOccurs="0"/>
            <xs:element name="ConsequentSetting" type="guha:BASettingRef" minOccurs="0"/>
            <xs:element name="ConditionSetting" type="guha:BASettingRef" minOccurs="0"/>
            <xs:element name="GeneralSetting" type="guha:GeneralSetting" minOccurs="0"
                maxOccurs="unbounded"/>
            <!-- The  InterestMeasureSetting type from GUHA namespace cannot be reused, because it asserts that interest measures are mandatory,
                but they are optional-->
            <xs:element name="InterestMeasureSetting" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="InterestMeasureThreshold" maxOccurs="unbounded"
                            minOccurs="0">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:choice>
                                        <xs:element name="InterestMeasure" type="arf:IMList"/>
                                        <xs:element name="Formula" type="guha:Formula"/>
                                    </xs:choice>
                                    <xs:element name="Threshold" type="xs:decimal" minOccurs="0"/>
                                    <xs:element name="CompareType" type="guha:CompareType"
                                        minOccurs="0"/>
                                    <xs:element name="SignificanceLevel" type="xs:decimal"
                                        minOccurs="0"/>
                                </xs:sequence>
                                <xs:attribute name="id" type="xs:NMTOKEN" use="required"/>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="match">
        <xs:restriction base="xs:string">
            <!-- all referenced BAs need to appear together in one DBA and this DBA must not contain any other BAs -->
            <xs:enumeration value="requireListed_exclusive"/>
            <!-- all referenced BAs need to appear together in one DBA, but this DBA can contain other BAs.  -->
            <xs:enumeration value="requireListed_notexclusive"/>
            <!-- DBA complying to this DBASetting must link via BARefs to BAs referenced via BASettingRefs either directly or indirectly, via several intermediate BBAs  -->
            <xs:enumeration value="traverseOnly"/>
        </xs:restriction>
    </xs:simpleType>


    
</xs:schema>

=== KIZI/EasyMiner-XML/sampledata/query/ar-builder-query-pmml-preprocessed.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- ARBuilder output - background association rules  -->
<ar:ARBuilder mode="AssociationRules" xmlns:ar="http://keg.vse.cz/ns/arbuilder0_1"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://keg.vse.cz/ns/arbuilder0_1 http://sewebar.vse.cz/schemas/ARBuilder0_1.xsd">
    <!-- Copy of datadictionary -->
    <DataDescription>
    <Dictionary  numberOfFields="4"  sourceType="PMML"  sourceName="Barbora">    
        <Field name="statusAgregovane" optype="categorical" dataType="string" derived="true">       
            <Category frequency="2116">dobry</Category>         
            <Category frequency="4065">stredni</Category>        
            <Category frequency="289">spatny</Category>                
        </Field>
        <Field name="duration" optype="continuous" dataType="integer" derived="true">        
            <Category frequency="4999">Nad 2 roky vcetne</Category>        
            <Category frequency="1243">13 az 23</Category>        
            <Category frequency="1181">Rok</Category>        
        </Field>
        <Field dataType="string" optype="categorical" name="district" derived="true">
            <Category frequency="209">Brno</Category>        
            <Category frequency="710">Praha</Category>        
            <Category frequency="5262">Other</Category>        
        </Field>
        <Field dataType="string" optype="categorical" name="sex" derived="true">
            <Category frequency="6181">F</Category>        
        </Field>
    </Dictionary>    
        </DataDescription>
    <AssociationRules>
        <BBA id="1">
            <Text>duration(Nad 2 roky vcetne)</Text>
            <FieldRef>duration</FieldRef>
            <CatRef>Nad 2 roky vcetne</CatRef>
        </BBA>
        <BBA id="2">
            <Text>statusAgregovane(dobry,stredni)</Text>
            <FieldRef>statusAgregovane</FieldRef>
            <CatRef>dobry</CatRef>
            <CatRef>stredni</CatRef>
        </BBA>
        <BBA id="3">
            <Text>district(Praha)</Text>
            <FieldRef>district</FieldRef>
            <CatRef>Praha</CatRef>
        </BBA>
        <BBA id="4">
            <Text>sex(female)</Text>
            <FieldRef>sex</FieldRef>
            <CatRef>female</CatRef>
        </BBA>
        <BBA id="5">
            <Text>duration(rok)</Text>
            <FieldRef>duration</FieldRef>
            <CatRef>rok</CatRef>
        </BBA>
        <DBA id="6" connective="Negation">
            <BARef>3</BARef>
        </DBA>
        <DBA id="7" connective="Conjunction">
            <BARef>1</BARef>
            <BARef>6</BARef>
        </DBA>
        <AssociationRule antecedent="7" consequent="2">
            <IMValue name="Support">0.55282316777220514479</IMValue>
            <IMValue name="Average Difference">0.1414</IMValue>
            <IMValue name="Kulczynski">0.8138</IMValue>
            <FourFtTable a="3586" b="874" c="768" d="953"/>
        </AssociationRule>
    </AssociationRules>
</ar:ARBuilder>

=== KIZI/EasyMiner-XML/sampledata/query/ARQuery-loose.xml
<?xml version="1.0" encoding="utf-8"?>
    
<?oxygen SCHSchema="http://sewebar.vse.cz/schemas/ARQuery_t1_0_1.sch"?>
<arb:ARBuilder xmlns:arb="http://keg.vse.cz/ns/arbuilder0_1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://keg.vse.cz/ns/arbuilder0_1 http://sewebar.vse.cz/schemas/ARBuilder0_1.xsd">
   <DataDescription xmlns:ar="http://keg.vse.cz/ns/arbuilder0_1" xmlns:guha="http://keg.vse.cz/ns/GUHA0.1rev1">
        
      <Dictionary sourceSubType="DataDictionary" sourceType="PMML" default="true">
            
         <Field name="Age">
                
            <Interval leftMargin="21" rightMargin="67" closure="closedClosed"/>
                
            <Category>&lt;21;31)</Category>
                
            <Category>&lt;31;41)</Category>
                
            <Category>&lt;41;51)</Category>
                
            <Category>&lt;51;61)</Category>
                
            <Category>&lt;61;71)</Category>
            
         </Field>
            
         <Field name="amount">
                
            <Interval leftMargin="4980" rightMargin="590820" closure="closedClosed"/>
                
            <Category>&lt; 20</Category>
                
            <Category>&lt;20;50)</Category>
                
            <Category>&lt;50;100)</Category>
                
            <Category>&lt;100;250)</Category>
                
            <Category>&lt;250;500)</Category>
                
            <Category>&gt;= 500</Category>
            
         </Field>
            
         <Field name="District">
                
            <Category>Benesov</Category>
                
            <Category>Beroun</Category>
                
            <Category>Blansko</Category>
                
            <Category>Breclav</Category>
                
            <Category>Brno</Category>
                
            <Category>Brno - venkov</Category>
                
            <Category>Bruntal</Category>
                
            <Category>Ceska Lipa</Category>
                
            <Category>Ceske Budejovice</Category>
                
            <Category>Cesky Krumlov</Category>
                
            <Category>Decin</Category>
                
            <Category>Domazlice</Category>
                
            <Category>Frydek - Mistek</Category>
                
            <Category>Havlickuv Brod</Category>
                
            <Category>Hodonin</Category>
                
            <Category>Hradec Kralove</Category>
                
            <Category>Cheb</Category>
                
            <Category>Chomutov</Category>
                
            <Category>Chrudim</Category>
                
            <Category>Jablonec n. Nisou</Category>
                
            <Category>Jesenik</Category>
                
            <Category>Jicin</Category>
                
            <Category>Jihlava</Category>
                
            <Category>Jindrichuv Hradec</Category>
                
            <Category>Karlovy Vary</Category>
                
            <Category>Karvina</Category>
                
            <Category>Kladno</Category>
                
            <Category>Klatovy</Category>
                
            <Category>Kolin</Category>
                
            <Category>Kromeriz</Category>
                
            <Category>Kutna Hora</Category>
                
            <Category>Liberec</Category>
                
            <Category>Litomerice</Category>
                
            <Category>Louny</Category>
                
            <Category>Melnik</Category>
                
            <Category>Mlada Boleslav</Category>
                
            <Category>Most</Category>
                
            <Category>Nachod</Category>
                
            <Category>Novy Jicin</Category>
                
            <Category>Nymburk</Category>
                
            <Category>Olomouc</Category>
                
            <Category>Opava</Category>
                
            <Category>Ostrava - mesto</Category>
                
            <Category>Pardubice</Category>
                
            <Category>Pelhrimov</Category>
                
            <Category>Pisek</Category>
                
            <Category>Plzen</Category>
                
            <Category>Plzen - jih</Category>
                
            <Category>Plzen - sever</Category>
                
            <Category>Praha</Category>
                
            <Category>Praha - vychod</Category>
                
            <Category>Praha - zapad</Category>
                
            <Category>Prachatice</Category>
                
            <Category>Prerov</Category>
                
            <Category>Pribram</Category>
                
            <Category>Prostejov</Category>
                
            <Category>Rakovnik</Category>
                
            <Category>Rokycany</Category>
                
            <Category>Rychnov nad Kneznou</Category>
                
            <Category>Semily</Category>
                
            <Category>Sokolov</Category>
                
            <Category>Strakonice</Category>
                
            <Category>Sumperk</Category>
                
            <Category>Svitavy</Category>
                
            <Category>Tabor</Category>
                
            <Category>Tachov</Category>
                
            <Category>Teplice</Category>
                
            <Category>Trebic</Category>
                
            <Category>Trutnov</Category>
                
            <Category>Uherske Hradiste</Category>
                
            <Category>Usti nad Labem</Category>
                
            <Category>Usti nad Orlici</Category>
                
            <Category>Vsetin</Category>
                
            <Category>Vyskov</Category>
                
            <Category>Zdar nad Sazavou</Category>
                
            <Category>Zlin</Category>
                
            <Category>Znojmo</Category>
            
         </Field>
            
         <Field name="payments">
                
            <Interval leftMargin="304" rightMargin="41728" closure="closedClosed"/>
                
            <Category>(0;1&gt;</Category>
                
            <Category>(1;2&gt;</Category>
                
            <Category>(2;3&gt;</Category>
                
            <Category>(3;4&gt;</Category>
                
            <Category>(4;5&gt;</Category>
                
            <Category>(5;6&gt;</Category>
                
            <Category>(6;7&gt;</Category>
                
            <Category>(7;8&gt;</Category>
                
            <Category>(8;9&gt;</Category>
                
            <Category>(9;10&gt;</Category>
            
         </Field>
            
         <Field name="Salary">
                
            <Interval leftMargin="8110" rightMargin="12541" closure="closedClosed"/>
                
            <Category>low</Category>
                
            <Category>avg</Category>
                
            <Category>high</Category>
            
         </Field>
            
         <Field name="Sex">
                
            <Category>Yes</Category>
                
            <Category>No</Category>
            
         </Field>
            
         <Field name="status">
                
            <Category>A</Category>
                
            <Category>C</Category>
                
            <Category>B</Category>
                
            <Category>D</Category>
            
         </Field>
        
      </Dictionary>
    
   </DataDescription>
   <ARQuery>
      <BBASettings>
         <BBASetting id="1">
            <Text>Age</Text>
            <FieldRef dictionary="DataDictionary">Age</FieldRef>
            <Coefficient>
               <Type>At least one from listed</Type>
               <Category>&lt;21;67&gt;</Category>
            </Coefficient>
         </BBASetting>
         <BBASetting id="3">
            <Text>District</Text>
            <FieldRef dictionary="DataDictionary">District</FieldRef>
            <Coefficient>
               <Type>At least one from listed</Type>
               <Category>Praha</Category>
            </Coefficient>
         </BBASetting>
      </BBASettings>
      <DBASettings>
         <DBASetting id="2" type="Literal">
            <BASettingRef>1</BASettingRef>
            <LiteralSign>Both</LiteralSign>
         </DBASetting>
         <DBASetting id="4" type="Literal">
            <BASettingRef>3</BASettingRef>
            <LiteralSign>Both</LiteralSign>
         </DBASetting>
      </DBASettings>
      <GeneralSetting>
         <Scope>
            <RulePart>Antecedent</RulePart>
            <RulePart>Consequent</RulePart>
            <RulePart>Condition</RulePart>
         </Scope>
         <ApplyRecursively>true</ApplyRecursively>
         <MandatoryPresenceConstraint>
            <MandatoryBA>2</MandatoryBA>
            <MandatoryBA>4</MandatoryBA>
         </MandatoryPresenceConstraint>
      </GeneralSetting>
      <InterestMeasureSetting>
         <InterestMeasureThreshold id="1">
            <InterestMeasure>Any Interest Measure</InterestMeasure>
         </InterestMeasureThreshold>
      </InterestMeasureSetting>
   </ARQuery>
</arb:ARBuilder>
