=== KIZI/EasyMiner-XML/validation/DataDescription0_1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://keg.vse.cz/ns/datadescription0_1"
    xmlns="http://keg.vse.cz/ns/datadescription0_1" elementFormDefault="unqualified"
    xmlns:data="http://keg.vse.cz/ns/datadescription0_1" attributeFormDefault="unqualified">
    <xs:element name="DataDescription" type="DataDescription"/>

    <xs:complexType name="DataDescription">
        <xs:sequence>
            <xs:element name="Dictionary" type="Dictionary" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="DictionaryMapping" type="DictionaryMapping" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="DictionaryMapping">
        <xs:sequence>
            <xs:element name="ValueMapping" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Field" minOccurs="1" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:choice maxOccurs="unbounded">
                                        <xs:element name="Value" type="xs:string"/>
                                        <xs:element name="Interval">
                                            <xs:complexType>
                                                <xs:attribute name="closure" use="required">
                                                  <xs:simpleType>
                                                  <xs:restriction base="xs:string">
                                                  <xs:enumeration value="openClosed"/>
                                                  <xs:enumeration value="openOpen"/>
                                                  <xs:enumeration value="closedOpen"/>
                                                  <xs:enumeration value="closedClosed"/>
                                                  </xs:restriction>
                                                  </xs:simpleType>
                                                </xs:attribute>
                                                <xs:attribute name="leftMargin" type="xs:double"/>
                                                <xs:attribute name="rightMargin" type="xs:double"/>
                                            </xs:complexType>

                                        </xs:element>
                                    </xs:choice>
                                </xs:sequence>
                                <xs:attribute name="name" type="xs:string"/>
                                <xs:attribute name="dictionary">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:enumeration value="TransformationDictionary"/>
                                            <xs:enumeration value="DataDictionary"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name="orphan" type="xs:boolean" default="false"/>
                </xs:complexType>

            </xs:element>
        </xs:sequence>
    </xs:complexType>



    <xs:complexType name="Dictionary">
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="Field">
                <xs:complexType>
                    <xs:sequence minOccurs="1">
                        <xs:element name="AuxilliaryIdentifier" type="AuxilliaryIdentifier"
                            minOccurs="0" maxOccurs="unbounded"/>
                        <xs:element name="Statistics" type="Statistics" minOccurs="0"/>
                        <xs:sequence maxOccurs="unbounded" minOccurs="0">
                            <xs:choice>
                                <xs:element name="Interval" type="Interval" minOccurs="0"
                                    maxOccurs="unbounded"/>
                                <xs:element name="Category" type="Category" minOccurs="0"
                                    maxOccurs="unbounded"/>
                            </xs:choice>
                        </xs:sequence>
                    </xs:sequence>
                    <xs:attribute name="optype" type="OPTYPE"/>
                    <xs:attribute name="dataType" type="DATATYPE"/>
                    <xs:attribute name="name" type="xs:string"/>
                    <xs:attribute name="derived" type="xs:boolean"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="numberOfFields" type="xs:integer"/>
        <xs:attribute name="sourceType" type="sourceType"/>
        <xs:attribute name="sourceSubType" type="dictType"/>
        <xs:attribute name="sourceName" type="xs:string"/>
        <!-- complete =false means that e.g. only those fields and values which are referenced from the association rules in the file are  listed -->
        <xs:attribute name="complete" type="xs:boolean" default="true"/>
        <xs:attribute name="default" type="xs:boolean" default="false"/>
    </xs:complexType>


    <xs:simpleType name="dictType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="TransformationDictionary"/>
            <xs:enumeration value="DataDictionary"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="AuxilliaryIdentifier">
        <xs:sequence>
            <xs:element name="Name" type="xs:string"/>
            <xs:element name="Value" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="display" type="xs:boolean" default="false"/>
    </xs:complexType>
    <xs:complexType name="Category">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="frequency" type="xs:integer"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="sourceType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="PMML"/>
            <xs:enumeration value="BKEF"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="OPTYPE">
        <xs:restriction base="xs:string">
            <xs:enumeration value="categorical"/>
            <xs:enumeration value="ordinal"/>
            <xs:enumeration value="continuous"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="Statistics">
        <xs:sequence>
            <xs:element name="Min" type="xs:double"/>
            <xs:element name="Max" type="xs:double"/>
            <xs:element name="Average" type="xs:double"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Interval">
        <xs:attribute name="closure" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="openClosed"/>
                    <xs:enumeration value="openOpen"/>
                    <xs:enumeration value="closedOpen"/>
                    <xs:enumeration value="closedClosed"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="leftMargin" type="xs:double"/>
        <xs:attribute name="rightMargin" type="xs:double"/>
        <xs:attribute name="binName" type="xs:string"/>
    </xs:complexType>

    <xs:simpleType name="DATATYPE">
        <xs:restriction base="xs:string">
            <xs:enumeration value="string"/>
            <xs:enumeration value="integer"/>
            <xs:enumeration value="float"/>
            <xs:enumeration value="double"/>
            <xs:enumeration value="date"/>
            <xs:enumeration value="time"/>
            <xs:enumeration value="dateTime"/>
            <xs:enumeration value="dateDaysSince[0]"/>
            <xs:enumeration value="dateDaysSince[1960]"/>
            <xs:enumeration value="dateDaysSince[1970]"/>
            <xs:enumeration value="dateDaysSince[1980]"/>
            <xs:enumeration value="timeSeconds"/>
            <xs:enumeration value="dateTimeSecondsSince[0]"/>
            <xs:enumeration value="dateTimeSecondsSince[1960]"/>
            <xs:enumeration value="dateTimeSecondsSince[1970]"/>
            <xs:enumeration value="dateTimeSecondsSince[1980]"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== KIZI/EasyMiner-XML/sampledata/query/XQUERYgeneratedDataDescription-barbora.xml
<dd:DataDescription xmlns:dd="http://keg.vse.cz/ns/datadescription0_1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:pmml="http://www.dmg.org/PMML-4_0" xsi:schemaLocation="http://keg.vse.cz/ns/datadescription0_1 http://sewebar.vse.cz/schemas/DataDescription0_1.xsd"><Dictionary sourceSubType="DataDictionary" sourceType="PMML" default="true"><Field name="Age"><Interval leftMargin="21" rightMargin="67" closure="closedClosed"/><Category>&lt;21;31)</Category><Category>&lt;31;41)</Category><Category>&lt;41;51)</Category><Category>&lt;51;61)</Category><Category>&lt;61;71)</Category></Field><Field name="amount"><Interval leftMargin="4980" rightMargin="590820" closure="closedClosed"/><Category>&lt; 20</Category><Category>&lt;20;50)</Category><Category>&lt;50;100)</Category><Category>&lt;100;250)</Category><Category>&lt;250;500)</Category><Category>>= 500</Category></Field><Field name="District"><Category>Benesov</Category><Category>Beroun</Category><Category>Blansko</Category><Category>Breclav</Category><Category>Brno</Category><Category>Brno - venkov</Category><Category>Bruntal</Category><Category>Ceska Lipa</Category><Category>Ceske Budejovice</Category><Category>Cesky Krumlov</Category><Category>Decin</Category><Category>Domazlice</Category><Category>Frydek - Mistek</Category><Category>Havlickuv Brod</Category><Category>Hodonin</Category><Category>Hradec Kralove</Category><Category>Cheb</Category><Category>Chomutov</Category><Category>Chrudim</Category><Category>Jablonec n. Nisou</Category><Category>Jesenik</Category><Category>Jicin</Category><Category>Jihlava</Category><Category>Jindrichuv Hradec</Category><Category>Karlovy Vary</Category><Category>Karvina</Category><Category>Kladno</Category><Category>Klatovy</Category><Category>Kolin</Category><Category>Kromeriz</Category><Category>Kutna Hora</Category><Category>Liberec</Category><Category>Litomerice</Category><Category>Louny</Category><Category>Melnik</Category><Category>Mlada Boleslav</Category><Category>Most</Category><Category>Nachod</Category><Category>Novy Jicin</Category><Category>Nymburk</Category><Category>Olomouc</Category><Category>Opava</Category><Category>Ostrava - mesto</Category><Category>Pardubice</Category><Category>Pelhrimov</Category><Category>Pisek</Category><Category>Plzen</Category><Category>Plzen - jih</Category><Category>Plzen - sever</Category><Category>Praha</Category><Category>Praha - vychod</Category><Category>Praha - zapad</Category><Category>Prachatice</Category><Category>Prerov</Category><Category>Pribram</Category><Category>Prostejov</Category><Category>Rakovnik</Category><Category>Rokycany</Category><Category>Rychnov nad Kneznou</Category><Category>Semily</Category><Category>Sokolov</Category><Category>Strakonice</Category><Category>Sumperk</Category><Category>Svitavy</Category><Category>Tabor</Category><Category>Tachov</Category><Category>Teplice</Category><Category>Trebic</Category><Category>Trutnov</Category><Category>Uherske Hradiste</Category><Category>Usti nad Labem</Category><Category>Usti nad Orlici</Category><Category>Vsetin</Category><Category>Vyskov</Category><Category>Zdar nad Sazavou</Category><Category>Zlin</Category><Category>Znojmo</Category></Field><Field name="payments"><Interval leftMargin="304" rightMargin="41728" closure="closedClosed"/><Category>(0;1></Category><Category>(1;2></Category><Category>(2;3></Category><Category>(3;4></Category><Category>(4;5></Category><Category>(5;6></Category><Category>(6;7></Category><Category>(7;8></Category><Category>(8;9></Category><Category>(9;10></Category></Field><Field name="Salary"><Interval leftMargin="8110" rightMargin="12541" closure="closedClosed"/><Category>low</Category><Category>avg</Category><Category>high</Category></Field><Field name="Sex"><Category>Yes</Category><Category>No</Category></Field><Field name="status"><Category>A</Category><Category>C</Category><Category>B</Category><Category>D</Category></Field></Dictionary></dd:DataDescription>

=== KIZI/EasyMiner-XML/sampledata/query/PMMLDataDictionary2DataDescription-barbora.xml
<?xml version="1.0" encoding="utf-8"?><dd:DataDescription xmlns:dd="http://keg.vse.cz/ns/datadescription0_1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:pmml="http://www.dmg.org/PMML-4_0" xsi:schemaLocation="http://keg.vse.cz/ns/datadescription0_1 http://sewebar.vse.cz/schemas/DataDescription0_1.xsd"><Dictionary numberOfFields="10" sourceType="PMML" sourceName="/pmml:PMML/pmml:Header/pmml:Extension[@name='metabase']/@value"><Field name="Age" optype="continuous" dataType="integer">
			
			
			<Interval closure="closedClosed" leftMargin="21.000000" rightMargin="67.000000"/>
		</Field><Field name="amount" optype="continuous" dataType="integer">
			
			
			<Interval closure="closedClosed" leftMargin="4980.000000" rightMargin="590820.000000"/>
		</Field><Field name="birth_number" optype="continuous" dataType="integer">
			
			
			<Interval closure="closedClosed" leftMargin="350129.000000" rightMargin="806207.000000"/>
		</Field><Field name="District" optype="categorical" dataType="string">
			
				<Category>Benesov</Category>
				<Category>Beroun</Category>
				<Category>Blansko</Category>
				<Category>Breclav</Category>
				<Category>Brno</Category>
				<Category>Brno - venkov</Category>
				<Category>Bruntal</Category>
				<Category>Ceska Lipa</Category>
				<Category>Ceske Budejovice</Category>
				<Category>Cesky Krumlov</Category>
				<Category>Decin</Category>
				<Category>Domazlice</Category>
				<Category>Frydek - Mistek</Category>
				<Category>Havlickuv Brod</Category>
				<Category>Hodonin</Category>
				<Category>Hradec Kralove</Category>
				<Category>Cheb</Category>
				<Category>Chomutov</Category>
				<Category>Chrudim</Category>
				<Category>Jablonec n. Nisou</Category>
				<Category>Jesenik</Category>
				<Category>Jicin</Category>
				<Category>Jihlava</Category>
				<Category>Jindrichuv Hradec</Category>
				<Category>Karlovy Vary</Category>
				<Category>Karvina</Category>
				<Category>Kladno</Category>
				<Category>Klatovy</Category>
				<Category>Kolin</Category>
				<Category>Kromeriz</Category>
				<Category>Kutna Hora</Category>
				<Category>Liberec</Category>
				<Category>Litomerice</Category>
				<Category>Louny</Category>
				<Category>Melnik</Category>
				<Category>Mlada Boleslav</Category>
				<Category>Most</Category>
				<Category>Nachod</Category>
				<Category>Novy Jicin</Category>
				<Category>Nymburk</Category>
				<Category>Olomouc</Category>
				<Category>Opava</Category>
				<Category>Ostrava - mesto</Category>
				<Category>Pardubice</Category>
				<Category>Pelhrimov</Category>
				<Category>Pisek</Category>
				<Category>Plzen</Category>
				<Category>Plzen - jih</Category>
				<Category>Plzen - sever</Category>
				<Category>Praha</Category>
				<Category>Praha - vychod</Category>
				<Category>Praha - zapad</Category>
				<Category>Prachatice</Category>
				<Category>Prerov</Category>
				<Category>Pribram</Category>
				<Category>Prostejov</Category>
				<Category>Rakovnik</Category>
				<Category>Rokycany</Category>
				<Category>Rychnov nad Kneznou</Category>
				<Category>Semily</Category>
				<Category>Sokolov</Category>
				<Category>Strakonice</Category>
				<Category>Sumperk</Category>
				<Category>Svitavy</Category>
				<Category>Tabor</Category>
				<Category>Tachov</Category>
				<Category>Teplice</Category>
				<Category>Trebic</Category>
				<Category>Trutnov</Category>
				<Category>Uherske Hradiste</Category>
				<Category>Usti nad Labem</Category>
				<Category>Usti nad Orlici</Category>
				<Category>Vsetin</Category>
				<Category>Vyskov</Category>
				<Category>Zdar nad Sazavou</Category>
				<Category>Zlin</Category>
				<Category>Znojmo</Category>
		</Field><Field name="duration" optype="continuous" dataType="integer">
			
			
			<Interval closure="closedClosed" leftMargin="12.000000" rightMargin="60.000000"/>
		</Field><Field name="loan_id" optype="continuous" dataType="integer">
			
			
			
			
			<Interval closure="closedClosed" leftMargin="4959.000000" rightMargin="19627.000000"/>
		</Field><Field name="payments" optype="continuous" dataType="integer">
			
			
			<Interval closure="closedClosed" leftMargin="304.000000" rightMargin="41728.000000"/>
		</Field><Field name="Salary" optype="continuous" dataType="integer">
			
			
			<Interval closure="closedClosed" leftMargin="8110.000000" rightMargin="12541.000000"/>
		</Field><Field name="Sex" optype="categorical" dataType="string">
			
				<Category>Yes</Category>
				<Category>No</Category>
		</Field><Field name="status" optype="categorical" dataType="string">
			
				<Category>A</Category>
				<Category>B</Category>
				<Category>C</Category>
				<Category>D</Category>
		</Field></Dictionary></dd:DataDescription>

=== KIZI/EasyMiner-XML/sampledata/query/XTMGetBKEFDescr2DataDescription-sampelresult-prepr.xml
<?xml version="1.0" encoding="utf-8"?>
<Dictionary xmlns="http://keg.vse.cz/ns/datadescription0_1" xmlns:d="http://keg.vse.cz/ns/datadescription0_1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xd="http://www.oxygenxml.com/ns/doc/xsl" xmlns:x="http://www.topicmaps.org/xtm/1.0/" sourceName="Barbora" sourceType="BKEF" xsi:schemaLocation="http://keg.vse.cz/ns/datadescription0_1 http://sewebar.vse.cz/schemas/DataDescription0_1.xsd">
   <Field name="AD Scale [Loan Quality]" optype="categorical" dataType="string" derived="true">
      <AuxilliaryIdentifier display="true">
         <Name>Preprocessing Hint</Name>
         <Value>Verbal [Loan Quality/AD Scale]</Value>
      </AuxilliaryIdentifier>
      <AuxilliaryIdentifier display="false">
         <Name>Bin Type</Name>
         <Value>Metafield Enumeration Bin</Value>
      </AuxilliaryIdentifier>
      <Category>Bad</Category>
      <Category>Good</Category>
      <Category>Medium</Category>
   </Field>
   <Field name="months [Loan Duration]" optype="categorical" dataType="string" derived="true">
      <AuxilliaryIdentifier display="true">
         <Name>Preprocessing Hint</Name>
         <Value>coarse grained [Loan Duration / months]</Value>
      </AuxilliaryIdentifier>
      <AuxilliaryIdentifier display="false">
         <Name>Bin Type</Name>
         <Value>Metafield Interval Bin</Value>
      </AuxilliaryIdentifier>
      <Category>&lt;13;23&gt;</Category>
      <Category>&lt;0;12&gt;</Category>
      <Category>&lt;24;INF&gt;</Category>
   </Field>
</Dictionary>

=== KIZI/EasyMiner-XML/sampledata/query/XTMGetBKEFDescr2DataDescription-sampelresult.xml
<?xml version="1.0" encoding="utf-8"?>
<Dictionary xmlns="http://keg.vse.cz/ns/datadescription0_1" xmlns:d="http://keg.vse.cz/ns/datadescription0_1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xd="http://www.oxygenxml.com/ns/doc/xsl" xmlns:x="http://www.topicmaps.org/xtm/1.0/" sourceName="Barbora"  xsi:schemaLocation="http://keg.vse.cz/ns/datadescription0_1 http://sewebar.vse.cz/schemas/DataDescription0_1.xsd">
   <Field name="months [Loan Duration]" optype="continuous" dataType="string">
      <Interval leftMargin="0" rightMargin="99999999" closure="closedClosed"/>
   </Field>
   <Field name="Region [Area]" optype="categorical" dataType="string">
      <Category>Central Bohemia</Category>
      <Category>Moravia</Category>
      <Category>Eastern Bohemia</Category>
   </Field>
   <Field name="AD Scale [Loan Quality]" optype="categorical" dataType="string">
      <Category>C</Category>
      <Category>A</Category>
      <Category>D</Category>
      <Category>B</Category>
   </Field>
</Dictionary>
