=== KIZI/EasyMiner-XML/validation/fml.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 		xmlns:fml = "http://keg.vse.cz/fml"
    xmlns = "http://keg.vse.cz/fml" 		targetNamespace="http://keg.vse.cz/fml"
    elementFormDefault="qualified"
    >

    <xs:element name="FML">
        <xs:complexType>
            <xs:choice>
                <xs:element name="BKEFtoPMML">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="AppliesTo">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="BKEF">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="Document" type="Document"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="PMML">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element maxOccurs="unbounded" name="Document"
                                                  type="Document"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="FieldMappings">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="unbounded" minOccurs="1"
                                            name="FieldMapping" type="FieldMapping"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="Document">
        <xs:sequence>
            <xs:element name="Title"/>
            <xs:element name="URL"/>
            <xs:element name="Filename"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="FieldMapping">
        <xs:sequence>
            <xs:element name="MappingInfo">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Type" type="MatchingType"/>
                        <xs:element name="Confidence" type="MacthingConfidence"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element maxOccurs="2" minOccurs="2" name="Field" type="Field"/>
            <xs:choice>
                <xs:element name="ValueToValueMapping"/>
                <xs:element name="IntervalToValueMapping"/>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="MacthingConfidence">
        <xs:restriction base="xs:double">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="1"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="MatchingType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Partial"/>
            <xs:enumeration value="Complete"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="Metafield">
        <xs:choice>
            <xs:element name="AllowedValues" type="Metafield_AllowedValues"/>
            <xs:element name="PreprocessingHint" type="Metafield_PreprocessingHint"/>
        </xs:choice>
        <xs:attribute name="metaattribute" use="required"/>
        <xs:attribute name="format" use="required"/>
    </xs:complexType>
    <xs:complexType name="Metafield_AllowedValues"> </xs:complexType>
    <xs:complexType name="Metafield_PreprocessingHint">
        <xs:attribute name="name"/>
    </xs:complexType>



    <xs:complexType name="DataField">
        <xs:attribute name="name"/>
    </xs:complexType>
    <xs:complexType name="DerivedField">
        <xs:attribute name="name"/>
    </xs:complexType>
    <xs:complexType name="Field">
        <xs:choice>
            <xs:element name="Metafield" type="Metafield"/>
            <xs:element name="DataField" type="DataField"/>
            <xs:element name="DerivedField" type="DerivedField"/>
        </xs:choice>
        <xs:attribute name="type" type="FieldType"/>
        <xs:attribute name="id" type="xs:int"/>
    </xs:complexType>
    <xs:complexType name="ValueToValueMapping">
        <xs:sequence>
            <xs:element name="ExactlyMatchingValues" type="ExactlyMatchingValues"/>
            <xs:element maxOccurs="2" minOccurs="2" name="OrphanValues" type="OrphanValues"/>
            <xs:element name="ValueMappingSuggestions">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded" minOccurs="0" name="ValueMapping">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element maxOccurs="2" minOccurs="2" name="Field">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="Value" type="Value"/>
                                            </xs:sequence>
                                            <xs:attribute name="fieldid" type="xs:int"/>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name="Count" type="Count"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="FieldType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="bkef"/>
            <xs:enumeration value="pmml"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="ExactlyMatchingValues">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="Value" type="Value"/>
        </xs:sequence>
        <xs:attribute name="count" type="Count"/>
    </xs:complexType>
    <xs:simpleType name="Count">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="OrphanValues">
        <xs:sequence>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="0" name="Value" type="Value"/>
            </xs:sequence>
        </xs:sequence>
        <xs:attribute name="fieldid" type="xs:int"/>
        <xs:attribute name="count" type="Count"/>
    </xs:complexType>
    <xs:simpleType name="Value">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    <xs:complexType name="IntervalToValueMapping">
        <xs:sequence>
            <xs:element name="ValuesWithinInterval" type="ValuesIntervalRelationship"/>
            <xs:element name="ValuesOutsideInterval" type="ValuesIntervalRelationship"/>
            <xs:element name="EmptyPartOfInterval" type="xs:double"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="ValuesIntervalRelationship">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="Value" type="Value"/>
        </xs:sequence>
        <xs:attribute name="fieldid" type="xs:int"/>
        <xs:attribute name="count" type="Count"/>
    </xs:complexType>
</xs:schema>

=== KIZI/EasyMiner-XML/sampledata/fml/barbora-simple.xml
<?xml version="1.0" encoding="UTF-8"?>
<FML xmlns="http://keg.vse.cz/fml"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://keg.vse.cz/fml ../validation/fml.xsd">
    <BKEFtoPMML>       
        <AppliesTo>
            <BKEF>
                <Document>
                    <Title>Financial Dataset</Title>
                    <URL>http://sewebar.vse.cz/index.php/demo/39-bkef-specification/61-financialdatasetbarbora</URL>
                    <Filename>Barbora.xml</Filename>
                </Document>
            </BKEF>
            <PMML>
                <Document>
                    <Title>Barbora Financial Dataset</Title>
                    <URL>http://sewebar.vse.cz/index.php/demo/36-pmml-specifications/53-financial-dataset-barbora</URL>
                    <Filename>Barbora.pmml</Filename>
                </Document>
            </PMML>
        </AppliesTo>

        <FieldMappings>
            <FieldMapping>
                <MappingInfo>
                    <Type>Partial</Type>
                    <!-- There are some values that do not match-->
                    <Confidence>0.9</Confidence>
                </MappingInfo>
                <Field type="bkef" id="6">
                    <Metafield metaattribute="kvalita úvěru"
                        format="Points of International Loan Quality Scale">
                        <AllowedValues />
                    </Metafield>
                </Field>
                <Field type="pmml" id="5">
                    <DataField name="status"/>
                </Field>
                <!-- Specific values are matched if their STRING DISTANCE is zero-->
                <ValueToValueMapping>
                    <ExactlyMatchingValues count="4"> </ExactlyMatchingValues>
                    <OrphanValues fieldid="6" count="1">
                        <Value>E</Value>
                    </OrphanValues>
                    <OrphanValues fieldid="7" count="0"> </OrphanValues>
                </ValueToValueMapping>

            </FieldMapping>

            <FieldMapping>
                <MappingInfo>
                    <Type>Complete</Type>
                    <!-- All values match, byt there is nonzero EmptyPartOfInterval-->
                    <Confidence>0.95</Confidence>
                </MappingInfo>
                <Field type="bkef" id="4">
                    <Metafield metaattribute="trvání úvěru" format="months">
                        <AllowedValues/>
                    </Metafield>
                </Field>
                <Field type="pmml" id="3">
                    <DataField name="duration"/>
                </Field>
                <IntervalToValueMapping>
                    
                    <ValuesWithinInterval fieldid="4" count="6"/>
                    <ValuesOutsideInterval fieldid="3" count="0"/>

                    <!-- Values in PMML start from 12 and end at 60, while the interval in BKEF starts at 1 ending at 60
                        there is no PMML value in the <1;12> range, accounting for (11)/60
                    
                    -->
                    <EmptyPartOfInterval>0.1833</EmptyPartOfInterval>
                </IntervalToValueMapping>
            </FieldMapping>
            <FieldMapping>
                <MappingInfo>
                    <Type>Partial</Type>
                    <!-- Some values from BKEF could not be matched -->
                    <Confidence>0.7</Confidence>
                    <!-- Maybe we are mapping wrong fields altogether!-->
                </MappingInfo>
                <Field type="bkef" id="1">
                    <Metafield metaattribute="bydliště klienta" format="district">
                        <AllowedValues/>
                    </Metafield>
                </Field>
                <Field type="pmml" id="2">
                    <DataField name="district"></DataField>
                </Field>
                <!-- The value mapping suggestion covers the case, when the values do not EXACTLY match -->
                <ValueToValueMapping>                    
                    <ExactlyMatchingValues count="2"/>
                    <OrphanValues fieldid="1" count="1">
                        <Value>Ostatní</Value>
                    </OrphanValues>
                    <OrphanValues fieldid="2" count="1">
                        <Value>Other</Value>
                    </OrphanValues>                    
                    <ValueMappingSuggestions count="1">
                        <!-- Nabídnout na mapování hodnoty, které si zcela na základě řetězcového porovnání neshodují-->
                        <ValueMapping>
                            
                            <Field fieldid="1">
                                <Value>Praha</Value>
                            </Field>
                            <Field fieldid="2">
                                <Value>Prague</Value>
                            </Field>
                        </ValueMapping>
                    </ValueMappingSuggestions>
                </ValueToValueMapping>
            </FieldMapping>
        </FieldMappings>
    </BKEFtoPMML>
</FML>
